//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportInvent.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Seria { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string LastVhod { get; set; }
        public Nullable<int> TypeVhod { get; set; }
        public Nullable<int> UserGender { get; set; }
    
        public virtual GenderTable GenderTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
        public virtual VhodTable VhodTable { get; set; }
    }
}
